### ISSUE TITLE
ElementaryOS

### ISSUE THREAD

**Issue by aliceemanueli** [z0o0p/alohomora#19]
Good morning!  This app is not available in the ElementaryOS App Store... Please bring it to ElementaryOS.  Why do we miss it!

**Comment by z0o0p** [comment]
Hi @aliceemanueli, thank you for your request. I appreciate your love and support for Alohomora. I am excited to announce that I am currently working on re-releasing Alohomora and will keep you updated with the latest news.

**Comment by z0o0p** [comment]
I'm closing this issue. #18 is already created for migration to Flatpak.
