### ISSUE TITLE
Confirmation of Cipher Key

### ISSUE THREAD

**Issue by msmaldi** [z0o0p/alohomora#8]
I install this software, but a enter a cipher key, but I wrote the wrong password, a new text box for confirmation of cipher key prevents the error

Also, how a delete all files to make a new cipher?

**Comment by z0o0p** [comment]
@msmaldi if you know the current cipher key, then I would suggest you change the cipher key from the application to prevent random errors. Regarding the new text box, a better design is needed for ValidateScreen.

You can use applications like Seahorse to directly alter your cipher key.

**Comment by z0o0p** [comment]
FIxed by a recent commit and will be available in the next release. Closing this now.
